name: oci-distribution-conformance
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - name: Build
        run: cargo build
      - name: Start server
        run: cargo run &
        env:
          HOST: 0.0.0.0
          USERNAME: mytestuser
          PASSWORD: mytestpassword
          AUTH_ENABLED: false
      - name: Wait 5 seconds
        run: sleep 5
      - name: Run OCI Distribution Spec conformance tests
        uses: rosvik/oci-distribution-spec@v1.0
        env:
          OCI_ROOT_URL: http://0.0.0.0:8602
          OCI_NAMESPACE: mytestorg/mytestrepo
          OCI_TEST_PULL: 1
          OCI_TEST_PUSH: 1
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 0
          OCI_DEBUG: 0
          OCI_DELETE_MANIFEST_BEFORE_BLOBS: 0
